"use client";

/**
 * RetirementCalculator — Main page component.
 * UX Enhancements v2:
 *  ✓ AnimatedNumber counters on all metric cards
 *  ✓ Staggered card entrance animations
 *  ✓ Smooth results-section fade-up on first calculation
 *  ✓ Mobile-optimised classes (2-up cards, stacked breakdown, short tab labels)
 *  ✓ Print summary via window.print()
 *  ✓ Share summary modal (copy-to-clipboard)
 *  ✓ Tooltip hints on metric card labels
 *  ✓ "Reset to defaults" button
 *  ✓ WCAG 2.1 AA fully preserved
 */

import { useState, useRef, useMemo, useEffect, useCallback } from "react";
import { calculateRetirement, calculateStepUpRetirement, formatINR } from "@/lib/financeCalc";
import SliderInput    from "./SliderInput";
import ResultCard     from "./ResultCard";
import BarChart       from "./BarChart";
import DonutChart     from "./DonutChart";
import AnimatedNumber from "./AnimatedNumber";
import PrintSummary   from "./PrintSummary";
import SavePlanModal  from "./SavePlanModal";

// ─── Design tokens ─────────────────────────────────────────────────────────
const C = {
  blue:       "#224c87",
  blueDark:   "#1a3a6b",
  red:        "#b91c1c",
  redBrand:   "#da3832",
  greyText:   "#595959",
  greyBorder: "#919090",
  bgPage:     "#f4f7fb",
  bgCard:     "#ffffff",
  bgMuted:    "#eef3fb",
};

// Lifestyle bucket defaults
const BUCKET_DEFAULTS = {
  medicalEnabled:  false,
  medicalMonthly:  5000,    // ₹5,000/mo additional medical expense
  medicalInflation: 8,      // medical inflation typically higher
  travelEnabled:   false,
  travelMonthly:   3000,    // ₹3,000/mo travel & leisure
  legacyEnabled:   false,
  legacyMonthly:   2000,    // ₹2,000/mo legacy/dependents buffer
};

const DEFAULTS = {
  currentAge: 28, retirementAge: 60, lifeExpectancy: 85,
  currentAnnualExpenses: 600000,
  inflationRate: 6, preRetirementReturn: 12, postRetirementReturn: 7,
  stepUpRate: 10,
};

const TABS = [
  { tabId: "tab-accum",    panelId: "panel-accum",    full: "Accumulation Phase", short: "Accumulation" },
  { tabId: "tab-drawdown", panelId: "panel-drawdown", full: "Drawdown Phase",     short: "Drawdown"     },
  { tabId: "tab-table",    panelId: "panel-table",    full: "Year-by-Year Table", short: "Table"        },
  { tabId: "tab-compare",  panelId: "panel-compare",  full: "Flat vs Step-Up",   short: "Compare"      },
];

const sH = {   // section heading style
  fontSize: 10, fontWeight: 700, color: C.blue,
  fontFamily: "var(--font-montserrat), Montserrat, sans-serif",
  letterSpacing: "0.1em", textTransform: "uppercase", margin: "0 0 18px",
};

// ─── Share Modal ────────────────────────────────────────────────────────────
function ShareModal({ results, inputs, onClose }) {
  const [copied, setCopied] = useState(false);

  const summaryText = results ? `
Retirement Planning Summary
===========================
Monthly SIP Required:       ${formatINR(results.requiredMonthlySIP)}/mo
Retirement Corpus Needed:   ${formatINR(results.retirementCorpus)}
Total Invested:             ${formatINR(results.totalInvested)}
Estimated Returns:          ${formatINR(results.wealthGained)}
Inflation-Adj. Expenses:    ${formatINR(results.retirementAnnualExpense)}/yr

Assumptions
-----------
Current Age:        ${inputs.currentAge} yrs
Retirement Age:     ${inputs.retirementAge} yrs
Life Expectancy:    ${inputs.lifeExpectancy} yrs
Annual Expenses:    ${formatINR(inputs.currentAnnualExpenses)}
Inflation Rate:     ${inputs.inflationRate}%
Pre-ret. Return:    ${inputs.preRetirementReturn}%
Post-ret. Return:   ${inputs.postRetirementReturn}%

Generated by FinCal Retirement Calculator — Technex '26, IIT BHU
Disclaimer: Illustrative only. Not a guarantee of future returns.
`.trim() : "";

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(summaryText);
      setCopied(true);
      setTimeout(() => setCopied(false), 2500);
    } catch {
      // Fallback for browsers without clipboard API
      const el = document.createElement("textarea");
      el.value = summaryText;
      document.body.appendChild(el);
      el.select();
      document.execCommand("copy");
      document.body.removeChild(el);
      setCopied(true);
      setTimeout(() => setCopied(false), 2500);
    }
  };

  // Trap focus inside modal (WCAG 2.4.3)
  const modalRef = useRef(null);
  useEffect(() => {
    const firstFocusable = modalRef.current?.querySelector("button, [href], input, [tabindex]");
    firstFocusable?.focus();
    const handleKey = (e) => { if (e.key === "Escape") onClose(); };
    document.addEventListener("keydown", handleKey);
    return () => document.removeEventListener("keydown", handleKey);
  }, [onClose]);

  return (
    <div
      className="modal-overlay"
      role="dialog"
      aria-modal="true"
      aria-labelledby="share-modal-title"
      onClick={(e) => { if (e.target === e.currentTarget) onClose(); }}
    >
      <div className="modal-box" ref={modalRef}>
        {/* Modal header */}
        <div style={{
          display: "flex", justifyContent: "space-between", alignItems: "center",
          padding: "20px 24px 16px",
          borderBottom: "1px solid #dde6f5",
        }}>
          <h2 id="share-modal-title" style={{
            fontSize: 16, fontWeight: 800, color: C.blueDark,
            fontFamily: "var(--font-montserrat), Montserrat, sans-serif", margin: 0,
          }}>
            Share Your Plan
          </h2>
          <button
            onClick={onClose}
            aria-label="Close share modal"
            style={{
              background: "none", border: "none", fontSize: 22,
              color: C.greyText, cursor: "pointer", padding: "2px 6px",
              lineHeight: 1, borderRadius: 4,
            }}
          >
            ×
          </button>
        </div>

        {/* Metric summary */}
        <div style={{ padding: "16px 24px" }}>
          <div style={{
            display: "grid", gridTemplateColumns: "1fr 1fr",
            gap: 10, marginBottom: 16,
          }}>
            {[
              { label: "Monthly SIP",      value: formatINR(results.requiredMonthlySIP) },
              { label: "Target Corpus",    value: formatINR(results.retirementCorpus)   },
              { label: "Total Invested",   value: formatINR(results.totalInvested)      },
              { label: "Est. Returns",     value: formatINR(results.wealthGained)       },
            ].map(({ label, value }) => (
              <div key={label} style={{
                background: C.bgMuted, borderRadius: 8, padding: "10px 12px",
              }}>
                <div style={{ fontSize: 10, color: C.greyText,
                  fontFamily: "var(--font-montserrat), Montserrat, sans-serif",
                  fontWeight: 700, letterSpacing: "0.06em",
                  textTransform: "uppercase", marginBottom: 3 }}>
                  {label}
                </div>
                <div style={{ fontSize: 16, fontWeight: 900, color: C.blueDark,
                  fontFamily: "var(--font-montserrat), Montserrat, sans-serif" }}>
                  {value}
                </div>
              </div>
            ))}
          </div>

          {/* Text summary */}
          <pre style={{
            background: "#f9fafb", border: "1px solid #dde6f5",
            borderRadius: 8, padding: "12px 14px",
            fontSize: 11, fontFamily: "Arial, sans-serif",
            color: C.greyText, lineHeight: 1.6,
            overflowX: "auto", whiteSpace: "pre-wrap", margin: "0 0 14px",
          }}>
            {summaryText}
          </pre>

          {/* Action buttons */}
          <div style={{ display: "flex", gap: 10 }}>
            <button
              onClick={handleCopy}
              style={{
                flex: 1, padding: "10px 16px",
                background: copied ? "#166534" : C.blue,
                color: "#fff", border: "none", borderRadius: 8,
                fontSize: 13, fontWeight: 700, cursor: "pointer",
                fontFamily: "var(--font-montserrat), Montserrat, sans-serif",
                transition: "background 0.2s",
              }}
            >
              {copied ? "✓ Copied!" : "Copy to Clipboard"}
            </button>
            <button
              onClick={() => { onClose(); setTimeout(() => window.print(), 100); }}
              style={{
                flex: 1, padding: "10px 16px",
                background: "none", color: C.blue,
                border: `1.5px solid ${C.blue}`, borderRadius: 8,
                fontSize: 13, fontWeight: 700, cursor: "pointer",
                fontFamily: "var(--font-montserrat), Montserrat, sans-serif",
              }}
            >
              Print / Save PDF
            </button>
          </div>
        </div>

        <p style={{
          fontSize: 10, color: C.greyText, fontFamily: "Arial, sans-serif",
          lineHeight: 1.5, padding: "0 24px 16px", margin: 0,
        }}>
          Disclaimer: Illustrative only. Not a recommendation. Past performance may or may not be sustained in future.
        </p>
      </div>
    </div>
  );
}

// ─── Main Calculator ─────────────────────────────────────────────────────────
export default function RetirementCalculator() {
  const [currentAge,            setCurrentAge]            = useState(DEFAULTS.currentAge);
  const [retirementAge,         setRetirementAge]         = useState(DEFAULTS.retirementAge);
  const [lifeExpectancy,        setLifeExpectancy]        = useState(DEFAULTS.lifeExpectancy);
  const [currentAnnualExpenses, setCurrentAnnualExpenses] = useState(DEFAULTS.currentAnnualExpenses);
  const [inflationRate,         setInflationRate]         = useState(DEFAULTS.inflationRate);
  const [preRetirementReturn,   setPreRetirementReturn]   = useState(DEFAULTS.preRetirementReturn);
  const [postRetirementReturn,  setPostRetirementReturn]  = useState(DEFAULTS.postRetirementReturn);
  const [showAssumptions,       setShowAssumptions]       = useState(false);
  const [isStepUp,              setIsStepUp]              = useState(false);
  const [stepUpRate,            setStepUpRate]             = useState(10);
  const [activeTab,             setActiveTab]             = useState("tab-accum");
  const [showShare,             setShowShare]             = useState(false);
  const [showSavePlan,          setShowSavePlan]          = useState(false);
  const [savedCount,            setSavedCount]            = useState(0);
  const [hasAnimated,           setHasAnimated]           = useState(false);
  const [activeStep,            setActiveStep]            = useState(0); // 0=none, 1,2,3=done
  const [hasInteracted,         setHasInteracted]         = useState(false);

  // ── Lifestyle expense buckets ─────────────────────────────────────────────
  const [medicalEnabled,  setMedicalEnabled]  = useState(BUCKET_DEFAULTS.medicalEnabled);
  const [medicalMonthly,  setMedicalMonthly]  = useState(BUCKET_DEFAULTS.medicalMonthly);
  const [medicalInflation,setMedicalInflation]= useState(BUCKET_DEFAULTS.medicalInflation);
  const [travelEnabled,   setTravelEnabled]   = useState(BUCKET_DEFAULTS.travelEnabled);
  const [travelMonthly,   setTravelMonthly]   = useState(BUCKET_DEFAULTS.travelMonthly);
  const [legacyEnabled,   setLegacyEnabled]   = useState(BUCKET_DEFAULTS.legacyEnabled);
  const [legacyMonthly,   setLegacyMonthly]   = useState(BUCKET_DEFAULTS.legacyMonthly);
  const [planLoaded,            setPlanLoaded]            = useState(null);  // name of loaded plan

  // ── Load plan from planId prop (passed from CalculatorClient via URL param) ─
  useEffect(() => {
    if (typeof window === "undefined") return;
    const params = new URLSearchParams(window.location.search);
    const planId = params.get("plan");
    if (!planId) return;
    fetch(`/api/plans/${planId}`)
      .then((r) => r.json())
      .then((data) => {
        if (!data.success) return;
        const p = data.plan;
        setCurrentAge(p.currentAge);
        setRetirementAge(p.retirementAge);
        setLifeExpectancy(p.lifeExpectancy);
        setCurrentAnnualExpenses(p.currentAnnualExpenses);
        setInflationRate(p.inflationRate);
        setPreRetirementReturn(p.preRetirementReturn);
        setPostRetirementReturn(p.postRetirementReturn);
        if (p.stepUpRate > 0) { setIsStepUp(true); setStepUpRate(p.stepUpRate); }
        setPlanLoaded(p.name);
        setHasCalculated(true);
      })
      .catch(() => {});
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);
  const [calcError,             setCalcError]             = useState(null);

  const tabListRef = useRef(null);

  const validInput = retirementAge > currentAge + 1 && lifeExpectancy > retirementAge + 1;

  // ── Effective expenses including lifestyle buckets ────────────────────────
  const effectiveAnnualExpenses = useMemo(() => {
    let extra = 0;
    if (medicalEnabled) extra += medicalMonthly * 12;
    if (travelEnabled)  extra += travelMonthly  * 12;
    if (legacyEnabled)  extra += legacyMonthly  * 12;
    return currentAnnualExpenses + extra;
  }, [currentAnnualExpenses, medicalEnabled, medicalMonthly,
      travelEnabled, travelMonthly, legacyEnabled, legacyMonthly]);

  // Weighted inflation when medical bucket is active
  const effectiveInflation = useMemo(() => {
    if (!medicalEnabled) return inflationRate;
    const baseAnnual    = currentAnnualExpenses;
    const medicalAnnual = medicalMonthly * 12;
    const total         = baseAnnual + medicalAnnual;
    return total > 0
      ? ((baseAnnual * inflationRate) + (medicalAnnual * medicalInflation)) / total
      : inflationRate;
  }, [inflationRate, medicalEnabled, medicalMonthly, medicalInflation, currentAnnualExpenses]);

  const results = useMemo(() => {
    if (!validInput) return null;
    return calculateRetirement({
      currentAge, retirementAge, lifeExpectancy,
      currentAnnualExpenses, inflationRate,
      preRetirementReturn, postRetirementReturn,
    });
  }, [currentAge, retirementAge, lifeExpectancy,
      currentAnnualExpenses, inflationRate,
      preRetirementReturn, postRetirementReturn]);

  // Trigger entrance animation once on first valid result
  useEffect(() => {
    if (results && !hasAnimated) setHasAnimated(true);
  }, [results, hasAnimated]);

  const handleTabKeyNav = useCallback((e, currentTabId) => {
    if (e.key !== "ArrowRight" && e.key !== "ArrowLeft") return;
    e.preventDefault();
    const idx  = TABS.findIndex((t) => t.tabId === currentTabId);
    const next = TABS[(idx + (e.key === "ArrowRight" ? 1 : -1) + TABS.length) % TABS.length];
    setActiveTab(next.tabId);
    setTimeout(() => tabListRef.current?.querySelector(`#${next.tabId}`)?.focus(), 0);
  }, []);

  const handleReset = () => {
    setCurrentAge(DEFAULTS.currentAge);
    setRetirementAge(DEFAULTS.retirementAge);
    setLifeExpectancy(DEFAULTS.lifeExpectancy);
    setCurrentAnnualExpenses(DEFAULTS.currentAnnualExpenses);
    setInflationRate(DEFAULTS.inflationRate);
    setPreRetirementReturn(DEFAULTS.preRetirementReturn);
    setPostRetirementReturn(DEFAULTS.postRetirementReturn);
    setIsStepUp(false);
    setStepUpRate(DEFAULTS.stepUpRate);
    setMedicalEnabled(BUCKET_DEFAULTS.medicalEnabled);
    setMedicalMonthly(BUCKET_DEFAULTS.medicalMonthly);
    setMedicalInflation(BUCKET_DEFAULTS.medicalInflation);
    setTravelEnabled(BUCKET_DEFAULTS.travelEnabled);
    setTravelMonthly(BUCKET_DEFAULTS.travelMonthly);
    setLegacyEnabled(BUCKET_DEFAULTS.legacyEnabled);
    setLegacyMonthly(BUCKET_DEFAULTS.legacyMonthly);
  };

  // ── Always compute both modes for the Compare tab ──────────────────────────
  const comparisonResults = useMemo(() => {
    if (!validInput) return null;
    try {
      const params = {
        currentAge, retirementAge, lifeExpectancy,
        currentAnnualExpenses: effectiveAnnualExpenses,
        inflationRate: effectiveInflation,
        preRetirementReturn, postRetirementReturn,
      };
      const flat      = calculateRetirement(params);
      const rateToUse = stepUpRate > 0 ? stepUpRate : 10;
      const stepup    = calculateStepUpRetirement({ ...params, stepUpRate: rateToUse });
      return { flat, stepup, stepUpRateUsed: rateToUse };
    } catch { return null; }
  }, [
    validInput, currentAge, retirementAge, lifeExpectancy,
    effectiveAnnualExpenses, effectiveInflation,
    preRetirementReturn, postRetirementReturn, stepUpRate,
  ]);

  // ── Animate step indicator when results compute ──────────────────────────────
  useEffect(() => {
    if (!results) { setActiveStep(0); return; }
    setActiveStep(1);
    const t1 = setTimeout(() => setActiveStep(2), 350);
    const t2 = setTimeout(() => setActiveStep(3), 700);
    return () => { clearTimeout(t1); clearTimeout(t2); };
  }, [results]);

  const inputs = {
    currentAge, retirementAge, lifeExpectancy,
    currentAnnualExpenses, inflationRate,
    preRetirementReturn, postRetirementReturn,
    isStepUp, stepUpRate,
    // Lifestyle buckets
    effectiveAnnualExpenses, effectiveInflation,
    medicalEnabled, medicalMonthly, medicalInflation,
    travelEnabled,  travelMonthly,
    legacyEnabled,  legacyMonthly,
  };

  return (
    <>
      <a href="#main-content" className="skip-link">Skip to main content</a>

      <div style={{ minHeight: "100vh", background: `linear-gradient(155deg, ${C.bgPage} 0%, #e4edf9 100%)` }}>

        {/* ── HEADER ── */}
        <header role="banner" style={{
          background: C.blue, borderBottom: `4px solid ${C.redBrand}`, padding: "28px 0 22px",
        }}>
          <div className="calc-header-inner" style={{ maxWidth: 1140, margin: "0 auto", padding: "0 24px" }}>
            <p aria-hidden="true" style={{
              fontSize: 10, color: "rgba(255,255,255,0.6)",
              fontFamily: "var(--font-montserrat), Montserrat, sans-serif",
              fontWeight: 700, letterSpacing: "0.14em", textTransform: "uppercase", marginBottom: 8,
            }}>
              HDFC Mutual Fund × FinCal Innovation Hackathon — Technex &#8217;26
            </p>
            <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-end", gap: 16, flexWrap: "wrap" }}>
              <div>
                <h1 style={{
                  fontSize: "clamp(22px, 4vw, 34px)", fontWeight: 900, color: "#fff",
                  fontFamily: "var(--font-montserrat), Montserrat, sans-serif", margin: 0, lineHeight: 1.15,
                }}>
                  Retirement Planning Calculator
                </h1>
                <p style={{ fontSize: 14, color: "rgba(255,255,255,0.82)", margin: "8px 0 0", fontFamily: "Arial, sans-serif" }}>
                  Estimate your retirement corpus and the monthly SIP needed to build it.
                </p>
              </div>
              {/* Header action buttons */}
              {results && (
                <div style={{ display: "flex", gap: 10, flexShrink: 0 }}>
                  <button
                    onClick={() => setShowSavePlan(true)}
                    aria-label="Save your retirement plan"
                    style={{
                      background: "rgba(255,255,255,0.92)", color: C.blue,
                      border: "1.5px solid rgba(255,255,255,0.9)",
                      borderRadius: 8, padding: "8px 16px", fontSize: 12, fontWeight: 700,
                      cursor: "pointer", fontFamily: "var(--font-montserrat), Montserrat, sans-serif",
                    }}
                  >
                    💾 Save{savedCount > 0 ? ` (${savedCount})` : ""}
                  </button>
                  <button
                    onClick={() => setShowShare(true)}
                    aria-label="Share or print your retirement plan"
                    style={{
                      background: "rgba(255,255,255,0.15)", color: "#fff",
                      border: "1.5px solid rgba(255,255,255,0.5)",
                      borderRadius: 8, padding: "8px 16px", fontSize: 12, fontWeight: 700,
                      cursor: "pointer", fontFamily: "var(--font-montserrat), Montserrat, sans-serif",
                      backdropFilter: "blur(4px)",
                    }}
                  >
                    Share / Print
                  </button>
                  <a
                    href="/plans"
                    aria-label="View saved plans"
                    style={{
                      background: "rgba(255,255,255,0.15)", color: "#fff",
                      border: "1.5px solid rgba(255,255,255,0.5)",
                      borderRadius: 8, padding: "8px 16px", fontSize: 12, fontWeight: 700,
                      cursor: "pointer", fontFamily: "var(--font-montserrat), Montserrat, sans-serif",
                      backdropFilter: "blur(4px)", textDecoration: "none",
                      display: "inline-block",
                    }}
                  >
                    My Plans
                  </a>
                  <a
                    href="/analytics"
                    aria-label="View analytics dashboard"
                    style={{
                      background: "rgba(255,255,255,0.15)", color: "#fff",
                      border: "1.5px solid rgba(255,255,255,0.5)",
                      borderRadius: 8, padding: "8px 16px", fontSize: 12, fontWeight: 700,
                      cursor: "pointer", fontFamily: "var(--font-montserrat), Montserrat, sans-serif",
                      backdropFilter: "blur(4px)", textDecoration: "none",
                      display: "inline-block",
                    }}
                  >
                    Analytics
                  </a>
                </div>
              )}
            </div>
          </div>
        </header>

        {/* ── DISCLAIMER RIBBON ── */}
        <div style={{
          background: "#fff8e1", borderBottom: "1px solid #f5c518",
          padding: "6px 0",
        }}>
          <p style={{
            margin: 0, fontSize: 10, color: "#5a3e00",
            fontFamily: "Verdana, Arial, sans-serif", lineHeight: 1.5,
            maxWidth: 1140, marginLeft: "auto", marginRight: "auto",
            padding: "0 24px", textAlign: "center",
          }}>
            <strong style={{ color: "#da3832", fontFamily: "Montserrat, sans-serif" }}>Disclaimer: </strong>
            This tool has been designed for information purposes only. Actual results may vary depending on various
            factors involved in capital market. Investor should not consider above as a recommendation for any
            schemes of HDFC Mutual Fund. Past performance may or may not be sustained in future and is not a
            guarantee of any future returns.
          </p>
        </div>

        {/* ── STEP INDICATOR ── */}
        <div aria-hidden="true" style={{ background: "#fff", borderBottom: "1px solid #dde6f5" }}>
          <div style={{
            maxWidth: 1140, margin: "0 auto", padding: "12px 24px",
            display: "flex", gap: 8, flexWrap: "wrap", alignItems: "center",
          }}>
            {[
              { n: 1, text: "Inflate Expenses"  },
              { n: 2, text: "Retirement Corpus" },
              { n: 3, text: "Monthly SIP"       },
            ].map(({ n, text }, i) => (
              <div key={n} style={{ display: "flex", alignItems: "center", gap: 6 }}>
                {i > 0 && <div style={{ width: 20, height: 2, borderRadius: 1, background: n <= activeStep ? C.blue : "#dde6f5", margin: "0 2px", transition: "background 0.3s" }} />}
                <div style={{
                  width: 24, height: 24, borderRadius: "50%",
                  background: n <= activeStep ? C.blue : "#dde6f5",
                  color:      n <= activeStep ? "#fff" : C.greyText,
                  fontSize: 11, fontWeight: 800,
                  fontFamily: "var(--font-montserrat), Montserrat, sans-serif",
                  display: "flex", alignItems: "center", justifyContent: "center",
                  transition: "background 0.3s, color 0.3s, transform 0.2s",
                }}>{n}</div>
                <span style={{
                  fontSize: 11,
                  fontWeight: n <= activeStep ? 800 : 600,
                  color: n <= activeStep ? C.blueDark : C.greyText,
                  fontFamily: "var(--font-montserrat), Montserrat, sans-serif",
                  transition: "color 0.3s, font-weight 0.3s",
                }}>
                  {text}
                </span>
              </div>
            ))}
          </div>
        </div>

        {/* ── MAIN ── */}
        <main
          id="main-content"
          tabIndex={-1}
          className="calc-layout"
          style={{
            maxWidth: 1140, margin: "0 auto", padding: "28px 24px 60px",
            display: "grid", gridTemplateColumns: "minmax(290px, 390px) 1fr",
            gap: 24, alignItems: "start",
          }}
        >

          {/* ════ LEFT: INPUTS ════ */}
          <section aria-labelledby="inputs-heading" className="animate-slide-left">
            <div style={{
              background: C.bgCard, borderRadius: 16,
              boxShadow: "0 2px 20px rgba(34,76,135,0.08)",
            }}>
              <div className="inputs-card-header" style={{
                background: C.bgMuted, borderBottom: "1px solid #dde6f5",
                padding: "14px 22px", borderRadius: "16px 16px 0 0",
                display: "flex", alignItems: "center", justifyContent: "space-between",
              }}>
                <div style={{ display: "flex", alignItems: "center", gap: 10 }}>
                  <svg width={16} height={16} viewBox="0 0 24 24" fill="none"
                    stroke={C.blue} strokeWidth={2.5} aria-hidden="true" focusable="false">
                    <circle cx="12" cy="8" r="4"/>
                    <path d="M4 20c0-4 3.6-7 8-7s8 3 8 7"/>
                  </svg>
                  <h2 id="inputs-heading" style={{
                    fontSize: 14, fontWeight: 700, color: C.blue,
                    fontFamily: "var(--font-montserrat), Montserrat, sans-serif", margin: 0,
                  }}>Your Details</h2>
                </div>
                <button
                  onClick={handleReset}
                  aria-label="Reset all inputs to default values"
                  title="Reset to defaults"
                  style={{
                    background: "none", border: "1px solid #dde6f5",
                    color: C.greyText, fontSize: 11, cursor: "pointer",
                    fontFamily: "Arial, sans-serif", padding: "4px 10px",
                    borderRadius: 6, minHeight: 30,
                  }}
                >
                  Reset
                </button>
              </div>

              <div style={{ padding: "22px 22px 14px" }}>
                <h3 style={sH}>Age &amp; Timeline</h3>
                <SliderInput id="currentAge" label="Current Age"
                  value={currentAge} min={18} max={55} step={1}
                  display={(v) => `${v} yrs`}
                  onChange={(v) => {
                    setCurrentAge(v);
                    // Only push forward if retirement age is now too close
                    if (retirementAge < v + 2) setRetirementAge(v + 2);
                  }} />
                <SliderInput id="retirementAge" label="Retirement Age"
                  value={retirementAge} min={currentAge + 2} max={75} step={1}
                  display={(v) => `${v} yrs`}
                  onChange={(v) => {
                    setRetirementAge(v);
                    // Only push forward if life expectancy is now too close
                    if (lifeExpectancy < v + 2) setLifeExpectancy(v + 2);
                  }}
                  hint={`${retirementAge - currentAge} years to retirement`} />
                <SliderInput id="lifeExpectancy" label="Life Expectancy"
                  value={lifeExpectancy} min={retirementAge + 2} max={100} step={1}
                  display={(v) => `${v} yrs`}
                  onChange={(v) => setLifeExpectancy(v)}
                  hint={`${lifeExpectancy - retirementAge} retirement years to fund`} />

                <hr style={{ border: "none", borderTop: "1px solid #dde6f5", margin: "4px 0 22px" }} />
                <h3 style={sH}>Expenses</h3>
                <SliderInput id="expenses" label="Current Annual Expenses"
                  value={currentAnnualExpenses} min={120000} max={5000000} step={60000}
                  display={formatINR} onChange={setCurrentAnnualExpenses}
                  hint={`Monthly: ${formatINR(currentAnnualExpenses / 12)}`} />

                {/* ── LIFESTYLE BUCKETS ── */}
                <hr style={{ border: "none", borderTop: "1px solid #dde6f5", margin: "4px 0 16px" }} />
                <h3 style={sH}>Lifestyle &amp; Healthcare</h3>
                <p style={{ fontSize: 11, color: C.greyText, fontFamily: "Verdana, Arial, sans-serif",
                  margin: "0 0 14px", lineHeight: 1.6 }}>
                  Add optional expense buckets. Each applies its own inflation rate to your corpus target.
                  Illustrative only.
                </p>

                {[
                  {
                    id: "medical", label: "🏥 Medical / Healthcare",
                    enabled: medicalEnabled, setEnabled: setMedicalEnabled,
                    monthly: medicalMonthly, setMonthly: setMedicalMonthly,
                    inflation: medicalInflation, setInflation: setMedicalInflation,
                    showInflation: true,
                    hint: "Medical costs typically inflate faster than general inflation",
                  },
                  {
                    id: "travel", label: "✈️ Travel & Leisure",
                    enabled: travelEnabled, setEnabled: setTravelEnabled,
                    monthly: travelMonthly, setMonthly: setTravelMonthly,
                    showInflation: false,
                    hint: "Annual holidays, dining, leisure activities in retirement",
                  },
                  {
                    id: "legacy", label: "👨‍👩‍👧 Legacy / Dependents",
                    enabled: legacyEnabled, setEnabled: setLegacyEnabled,
                    monthly: legacyMonthly, setMonthly: setLegacyMonthly,
                    showInflation: false,
                    hint: "Support for dependents or estate planning buffer",
                  },
                ].map(({ id, label, enabled, setEnabled, monthly, setMonthly,
                          inflation, setInflation, showInflation, hint }) => (
                  <div key={id} style={{
                    border: `1.5px solid ${enabled ? C.blue : "#dde6f5"}`,
                    borderRadius: 10, marginBottom: 10, overflow: "hidden",
                    transition: "border-color 0.2s",
                  }}>
                    {/* Toggle header */}
                    <button
                      onClick={() => setEnabled(!enabled)}
                      aria-pressed={enabled}
                      aria-expanded={enabled}
                      aria-controls={`bucket-${id}`}
                      style={{
                        width: "100%", display: "flex", justifyContent: "space-between",
                        alignItems: "center", padding: "10px 14px",
                        background: enabled ? "#eef3fb" : "#f9fafb",
                        border: "none", cursor: "pointer",
                        transition: "background 0.2s",
                      }}
                    >
                      <span style={{
                        fontSize: 12, fontWeight: 700, color: enabled ? C.blueDark : C.greyText,
                        fontFamily: "var(--font-montserrat), Montserrat, sans-serif",
                      }}>{label}</span>
                      <span style={{
                        fontSize: 10, fontWeight: 700,
                        background: enabled ? C.blue : "#dde6f5",
                        color: enabled ? "#fff" : C.greyText,
                        borderRadius: 4, padding: "2px 8px",
                        fontFamily: "Arial, sans-serif",
                        transition: "background 0.2s, color 0.2s",
                      }}>{enabled ? "ON" : "OFF"}</span>
                    </button>

                    {/* Expanded controls */}
                    {enabled && (
                      <div id={`bucket-${id}`} style={{ padding: "12px 14px 4px" }}>
                        <SliderInput
                          id={`${id}-monthly`}
                          label="Monthly Amount"
                          value={monthly}
                          min={500} max={50000} step={500}
                          display={formatINR}
                          onChange={setMonthly}
                          hint={`Annual: ${formatINR(monthly * 12)}`}
                        />
                        {showInflation && (
                          <SliderInput
                            id={`${id}-inflation`}
                            label="Inflation Rate for this bucket"
                            value={inflation}
                            min={4} max={15} step={0.5}
                            display={(v) => `${v}%`}
                            onChange={setInflation}
                            hint={hint}
                          />
                        )}
                        {!showInflation && (
                          <p style={{ fontSize: 10, color: C.greyText,
                            fontFamily: "Verdana, Arial, sans-serif",
                            margin: "0 0 12px", lineHeight: 1.5 }}>{hint}</p>
                        )}
                      </div>
                    )}
                  </div>
                ))}

                {/* Effective expense summary when any bucket is active */}
                {(medicalEnabled || travelEnabled || legacyEnabled) && (
                  <div role="status" style={{
                    background: "#eef3fb", border: "1.5px solid #c7d9f5",
                    borderRadius: 8, padding: "10px 14px", marginBottom: 16,
                    fontSize: 11, fontFamily: "Verdana, Arial, sans-serif",
                    color: C.blueDark, lineHeight: 1.6,
                  }}>
                    <strong style={{ fontFamily: "Montserrat, sans-serif" }}>
                      Effective annual expenses:{" "}
                    </strong>
                    {formatINR(effectiveAnnualExpenses)}
                    {medicalEnabled && (
                      <span style={{ color: C.greyText }}>{" "}(incl. weighted inflation {effectiveInflation.toFixed(1)}%)</span>
                    )}
                  </div>
                )}

                <hr style={{ border: "none", borderTop: "1px solid #dde6f5", margin: "4px 0 22px" }} />
                <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 16 }}>
                  <h3 style={{ ...sH, margin: 0 }}>Return Assumptions</h3>
                  <button
                    aria-expanded={showAssumptions}
                    aria-controls="assumptions-panel"
                    onClick={() => setShowAssumptions(!showAssumptions)}
                    style={{
                      background: "none", border: "1px solid #dde6f5", color: C.blue,
                      fontSize: 12, cursor: "pointer", fontFamily: "Arial, sans-serif",
                      padding: "5px 10px", borderRadius: 6, minHeight: 36,
                    }}
                  >{showAssumptions ? "Collapse ▲" : "Edit all ▼"}</button>
                </div>

                {/* Always-visible chips */}
                <div style={{ display: "flex", gap: 6, flexWrap: "wrap", marginBottom: 18 }}>
                  {[
                    { label: "Inflation",        val: `${inflationRate}%`        },
                    { label: "Pre-ret. return",  val: `${preRetirementReturn}%`  },
                    { label: "Post-ret. return", val: `${postRetirementReturn}%` },
                  ].map(({ label, val }) => (
                    <div key={label} style={{
                      background: "#fff", border: "1px solid #dde6f5",
                      borderRadius: 6, padding: "5px 10px",
                      fontSize: 11, fontFamily: "Arial, sans-serif",
                    }}>
                      <span style={{ color: C.greyText }}>{label}: </span>
                      <strong style={{ color: C.blue }}>{val}</strong>
                    </div>
                  ))}
                </div>

                <div id="assumptions-panel">
                  {showAssumptions && (
                    <>
                      <SliderInput id="inflation" label="Inflation Rate"
                        value={inflationRate} min={2} max={12} step={0.5}
                        display={(v) => `${v}%`} onChange={setInflationRate}
                        hint="Applied to grow current expenses to retirement date" />
                      <SliderInput id="preReturn" label="Pre-Retirement Return"
                        value={preRetirementReturn} min={4} max={18} step={0.5}
                        display={(v) => `${v}%`} onChange={setPreRetirementReturn}
                        hint="Assumed annual return while accumulating corpus" />
                      <SliderInput id="postReturn" label="Post-Retirement Return"
                        value={postRetirementReturn} min={4} max={12} step={0.5}
                        display={(v) => `${v}%`} onChange={setPostRetirementReturn}
                        hint="Assumed annual return on corpus after retirement" />
                    </>
                  )}
                </div>

                <hr style={{ border: "none", borderTop: "1px solid #dde6f5", margin: "4px 0 22px" }} />

                {/* ── STEP-UP SIP TOGGLE ── */}
                <div>
                  {/* Toggle header */}
                  <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 12 }}>
                    <div>
                      <h3 style={{ ...sH, margin: "0 0 2px" }}>Step-Up SIP</h3>
                      <p style={{ fontSize: 11, color: C.greyText, margin: 0, fontFamily: "Arial, sans-serif" }}>
                        Increase SIP by a fixed % every year
                      </p>
                    </div>
                    {/* Toggle switch */}
                    <button
                      role="switch"
                      aria-checked={isStepUp}
                      aria-label={`Step-Up SIP is ${isStepUp ? "on" : "off"}`}
                      onClick={() => setIsStepUp(!isStepUp)}
                      style={{
                        width: 44, height: 24, borderRadius: 12,
                        background: isStepUp ? C.blue : "#dde6f5",
                        border: "none", cursor: "pointer",
                        position: "relative", transition: "background 0.2s",
                        flexShrink: 0,
                      }}
                    >
                      <span aria-hidden="true" style={{
                        position: "absolute",
                        top: 3, left: isStepUp ? 23 : 3,
                        width: 18, height: 18, borderRadius: "50%",
                        background: "#fff",
                        boxShadow: "0 1px 4px rgba(0,0,0,0.18)",
                        transition: "left 0.2s",
                        display: "block",
                      }} />
                    </button>
                  </div>

                  {/* Step-up rate slider — only shown when enabled */}
                  {isStepUp && (
                    <div style={{
                      background: C.bgMuted, borderRadius: 10,
                      border: `1.5px solid ${C.blue}22`,
                      padding: "14px 16px",
                      animation: "fadeUp 0.25s ease both",
                    }}>
                      <div style={{
                        fontSize: 11, color: C.greyText, fontFamily: "Arial, sans-serif",
                        marginBottom: 14, lineHeight: 1.5,
                        background: "#fff", borderRadius: 8,
                        padding: "8px 12px", border: "1px solid #dde6f5",
                      }}>
                        💡 Starting at <strong style={{ color: C.blue }}>{formatINR(results?.requiredMonthlySIP ?? 0)}/mo</strong>,
                        your SIP grows <strong style={{ color: C.blue }}>{stepUpRate}%</strong> every year —
                        reaching <strong style={{ color: C.blue }}>
                          {results?.finalMonthlySIP ? formatINR(results.finalMonthlySIP) : "—"}/mo
                        </strong> in the final year.
                        {results && (
                          <span style={{ color: "#166534" }}> That&apos;s a lower starting SIP vs flat ₹ every month.</span>
                        )}
                      </div>
                      <SliderInput
                        id="stepUpRate"
                        label="Annual SIP Increase"
                        value={stepUpRate} min={1} max={25} step={1}
                        display={(v) => `${v}% / yr`}
                        onChange={setStepUpRate}
                        hint="Your SIP will increase by this percentage every year"
                      />
                    </div>
                  )}
                </div>

              </div>
            </div>
          </section>

          {/* ════ RIGHT: RESULTS ════ */}
          <section aria-labelledby="results-heading" aria-live="polite">
            <h2 id="results-heading" className="sr-only">Calculation Results</h2>

            {/* ── ONBOARDING WELCOME — visible until results appear ── */}
            {!results && validInput && (
              <div className="animate-fade-up" style={{
                background: "linear-gradient(135deg, #224c87 0%, #1a3a6b 100%)",
                borderRadius: 16, padding: "32px 28px", marginBottom: 16,
                color: "#fff", textAlign: "center",
              }}>
                <div style={{ fontSize: 40, marginBottom: 16 }}>📊</div>
                <h3 style={{
                  fontSize: 20, fontWeight: 900, margin: "0 0 10px",
                  fontFamily: "var(--font-montserrat), Montserrat, sans-serif",
                }}>
                  Your Retirement Plan
                </h3>
                <p style={{
                  fontSize: 13, color: "rgba(255,255,255,0.8)", margin: "0 0 24px",
                  fontFamily: "Verdana, Arial, sans-serif", lineHeight: 1.7,
                }}>
                  Adjust the sliders on the left to see your personalised
                  retirement corpus and monthly SIP instantly.
                </p>
                <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr 1fr", gap: 12, marginBottom: 24 }}>
                  {[
                    { icon: "1️⃣", label: "Set your age & expenses" },
                    { icon: "2️⃣", label: "Choose return assumptions" },
                    { icon: "3️⃣", label: "See your SIP & corpus" },
                  ].map(({ icon, label }) => (
                    <div key={label} style={{
                      background: "rgba(255,255,255,0.12)", borderRadius: 10,
                      padding: "12px 8px", fontSize: 11,
                      fontFamily: "Arial, sans-serif", color: "rgba(255,255,255,0.9)",
                    }}>
                      <div style={{ fontSize: 20, marginBottom: 6 }}>{icon}</div>
                      {label}
                    </div>
                  ))}
                </div>
                <div style={{
                  background: "rgba(255,255,255,0.1)", borderRadius: 8,
                  padding: "10px 16px", fontSize: 11,
                  fontFamily: "Verdana, Arial, sans-serif",
                  color: "rgba(255,255,255,0.7)", lineHeight: 1.6,
                }}>
                  Results update live as you drag. All figures are illustrative only.
                </div>
              </div>
            )}

            {!validInput && (
              <div role="alert" aria-atomic="true" style={{
                background: "#fff8e1", border: "1px solid #f5c518", borderRadius: 12,
                padding: "16px 20px", fontSize: 14, color: "#5a3e00",
                fontFamily: "Arial, sans-serif", lineHeight: 1.5,
              }}>
                <strong>Please check your inputs:</strong> Retirement age must be greater than
                current age, and life expectancy must be greater than retirement age.
              </div>
            )}

            {validInput && calcError && (
              <div role="alert" aria-atomic="true" style={{
                background: "#fff1f2", border: "1px solid #fca5a5", borderRadius: 12,
                padding: "16px 20px", fontSize: 14, color: "#7f1d1d",
                fontFamily: "Arial, sans-serif", lineHeight: 1.5,
                display: "flex", alignItems: "flex-start", gap: 12,
              }}>
                <span aria-hidden="true" style={{ fontSize: 20, lineHeight: 1 }}>⚠️</span>
                <div>
                  <strong>Calculation error:</strong> {calcError}
                  <div style={{ marginTop: 8 }}>
                    <button
                      onClick={handleReset}
                      style={{
                        background: "#7f1d1d", color: "#fff", border: "none",
                        borderRadius: 6, padding: "6px 14px", fontSize: 12,
                        fontWeight: 700, cursor: "pointer",
                        fontFamily: "Montserrat, sans-serif",
                      }}
                    >
                      Reset to defaults
                    </button>
                  </div>
                </div>
              </div>
            )}

            {validInput && results && (
              <div className={hasAnimated ? "" : "results-enter"}>

                {/* ── METRIC CARDS ── */}
                <div className="metric-grid" style={{
                  display: "grid",
                  gridTemplateColumns: "repeat(auto-fit, minmax(155px, 1fr))",
                  gap: 12, marginBottom: 18,
                }}>
                  {[
                    {
                      label: isStepUp ? "Starting Monthly SIP" : "Monthly SIP Required",
                      accentColor: C.blue, large: true,
                      value: results.requiredMonthlySIP,
                      sub: isStepUp
                        ? `Grows ${stepUpRate}% yearly → ${formatINR(results.finalMonthlySIP)}/mo`
                        : `For ${results.yearsToRetirement} years starting today`,
                      tooltip: isStepUp
                        ? `First month SIP. Increases ${stepUpRate}% every year, reaching ${formatINR(results.finalMonthlySIP)}/mo in year ${results.yearsToRetirement}`
                        : "The monthly investment needed to reach your retirement corpus",
                    },
                    {
                      label: "Retirement Corpus Needed", accentColor: C.red, large: true,
                      value: results.retirementCorpus,
                      sub: `Required at age ${retirementAge}`,
                      tooltip: "Total savings needed on your retirement date",
                    },
                    {
                      label: "Inflation-Adjusted Expenses", accentColor: C.greyBorder,
                      value: results.retirementAnnualExpense,
                      sub: "Annual at retirement",
                      tooltip: `Your current expenses grown at ${inflationRate}% inflation for ${results.yearsToRetirement} years`,
                    },
                    {
                      label: "Total Amount Invested", accentColor: C.blue,
                      value: results.totalInvested,
                      sub: `Est. gains: ${formatINR(results.wealthGained)}`,
                      tooltip: isStepUp
                        ? "Total of all step-up SIP payments over the investment period"
                        : "Total SIP payments over the investment period",
                    },
                  ].map(({ label, value, sub, accentColor, large, tooltip }, idx) => (
                    <div
                      key={label}
                      className="animate-fade-up tooltip-wrapper"
                      style={{
                        animationDelay: `${idx * 0.06}s`,
                        position: "relative",   // tooltip anchors to THIS card
                      }}
                    >
                      <div style={{
                        background: C.bgCard, border: "1.5px solid #dde6f5",
                        borderRadius: 12, padding: large ? "20px 18px" : "14px 16px",
                        position: "relative", overflow: "hidden",
                        height: "100%",
                      }}>
                        <div aria-hidden="true" style={{
                          position: "absolute", top: 0, left: 0,
                          width: 4, height: "100%",
                          background: accentColor, borderRadius: "12px 0 0 12px",
                        }} />
                        <div style={{ paddingLeft: 10 }}>
                          <div style={{
                            fontSize: 10, color: C.greyText,
                            fontFamily: "var(--font-montserrat), Montserrat, sans-serif",
                            fontWeight: 700, letterSpacing: "0.08em",
                            textTransform: "uppercase", marginBottom: 6,
                          }}>
                            {label}
                          </div>
                          <div style={{
                            fontSize: large ? 24 : 20, fontWeight: 900,
                            color: C.blueDark,
                            fontFamily: "var(--font-montserrat), Montserrat, sans-serif",
                            lineHeight: 1.1,
                          }}>
                            <AnimatedNumber value={value} format={formatINR} duration={500} />
                          </div>
                          {sub && (
                            <div style={{ fontSize: 11, color: C.greyText, marginTop: 4, fontFamily: "Arial, sans-serif" }}>
                              {sub}
                            </div>
                          )}
                        </div>
                      </div>
                      {/* Tooltip — anchored to card, not grid row */}
                      <span className="tooltip-box" role="tooltip">{tooltip}</span>
                    </div>
                  ))}
                </div>

                {/* ── DONUT + LEGEND + FORMULA ── */}
                <div className="animate-scale-in" style={{
                  background: C.bgCard, borderRadius: 16,
                  boxShadow: "0 2px 20px rgba(34,76,135,0.07)",
                  padding: "20px 22px", marginBottom: 18,
                  animationDelay: "0.15s",
                }}>
                  <div className="breakdown-flex" style={{ display: "flex", flexWrap: "wrap", gap: 24, alignItems: "flex-start" }}>
                    <DonutChart invested={results.totalInvested} gains={results.wealthGained} />

                    <div style={{ flex: "1 1 160px" }}>
                      <h3 style={sH}>Corpus Breakdown at Retirement</h3>
                      <dl style={{ margin: 0 }}>
                        {[
                          { term: "Amount Invested",   val: results.totalInvested, color: C.blue },
                          { term: "Estimated Returns", val: results.wealthGained,  color: C.red  },
                        ].map(({ term, val, color }) => (
                          <div key={term} style={{ display: "flex", alignItems: "center", gap: 10, marginBottom: 10 }}>
                            <div aria-hidden="true" style={{ width: 11, height: 11, borderRadius: 2, background: color, flexShrink: 0 }} />
                            <dt style={{ fontSize: 13, color: C.greyText, fontFamily: "Arial, sans-serif", flex: 1 }}>{term}</dt>
                            <dd style={{ fontSize: 13, fontWeight: 700, color,
                              fontFamily: "var(--font-montserrat), Montserrat, sans-serif", margin: 0 }}>
                              <AnimatedNumber value={val} format={formatINR} />
                            </dd>
                          </div>
                        ))}
                        <div style={{ borderTop: "1px solid #dde6f5", paddingTop: 10, marginTop: 4,
                          display: "flex", alignItems: "center", gap: 10 }}>
                          <div aria-hidden="true" style={{ width: 11, height: 11, borderRadius: 2, background: C.blueDark, flexShrink: 0 }} />
                          <dt style={{ fontSize: 13, fontWeight: 700, color: C.blueDark, fontFamily: "Arial, sans-serif", flex: 1 }}>Total Corpus</dt>
                          <dd style={{ fontSize: 14, fontWeight: 900, color: C.blueDark,
                            fontFamily: "var(--font-montserrat), Montserrat, sans-serif", margin: 0 }}>
                            <AnimatedNumber value={results.retirementCorpus} format={formatINR} />
                          </dd>
                        </div>
                      </dl>
                    </div>

                    {/* Formula panel — hidden on mobile via CSS */}
                    <div className="formula-panel" style={{ flex: "1 1 180px", borderLeft: "2px solid #dde6f5", paddingLeft: 20 }}>
                      <h3 style={sH}>How It&#8217;s Calculated</h3>
                      <ol style={{ margin: 0, padding: 0, listStyle: "none" }}>
                        {[
                          {
                            title: "Inflate Expenses",
                            formula: `${formatINR(effectiveAnnualExpenses)} × (1+${effectiveInflation.toFixed(1)}%)^${results.yearsToRetirement}`,
                            result: `${formatINR(results.retirementAnnualExpense)}/yr`,
                          },
                          {
                            title: "PV of Annuity (Corpus)",
                            formula: `Expense × [(1−(1+r)^−${results.retirementDuration}) ÷ r]`,
                            result: formatINR(results.retirementCorpus),
                          },
                          {
                            title: "Required Monthly SIP",
                            formula: `Corpus × r ÷ [((1+r)^n−1)(1+r)]`,
                            result: `${formatINR(results.requiredMonthlySIP)}/mo`,
                          },
                        ].map(({ title, formula, result }, i) => (
                          <li key={i} style={{ marginBottom: 13, display: "flex", gap: 9 }}>
                            <div aria-hidden="true" style={{
                              width: 20, height: 20, borderRadius: "50%",
                              background: C.blue, color: "#fff",
                              fontSize: 10, fontWeight: 800,
                              fontFamily: "var(--font-montserrat), Montserrat, sans-serif",
                              display: "flex", alignItems: "center", justifyContent: "center",
                              flexShrink: 0, marginTop: 1,
                            }}>{i + 1}</div>
                            <div>
                              <div style={{ fontSize: 11, fontWeight: 700, color: C.blueDark,
                                fontFamily: "var(--font-montserrat), Montserrat, sans-serif" }}>{title}</div>
                              <div style={{ fontSize: 10, color: C.greyText, fontFamily: "Arial, sans-serif",
                                marginTop: 2, lineHeight: 1.5 }}>{formula}</div>
                              <div style={{ fontSize: 11, fontWeight: 700, color: C.blue,
                                fontFamily: "var(--font-montserrat), Montserrat, sans-serif", marginTop: 2 }}>= {result}</div>
                            </div>
                          </li>
                        ))}
                      </ol>
                    </div>
                  </div>
                </div>

                {/* ── TABBED CHARTS ── */}
                <div style={{
                  background: C.bgCard, borderRadius: 16,
                  boxShadow: "0 2px 20px rgba(34,76,135,0.07)",
                  marginBottom: 18, overflow: "hidden",
                }}>
                  <div role="tablist" aria-label="Corpus projection views"
                    ref={tabListRef}
                    style={{ display: "flex", borderBottom: "1px solid #dde6f5" }}>
                    {TABS.map((t) => (
                      <button
                        key={t.tabId}
                        id={t.tabId}
                        role="tab"
                        aria-selected={activeTab === t.tabId}
                        aria-controls={t.panelId}
                        tabIndex={activeTab === t.tabId ? 0 : -1}
                        onClick={() => setActiveTab(t.tabId)}
                        onKeyDown={(e) => handleTabKeyNav(e, t.tabId)}
                        style={{
                          flex: 1, padding: "11px 6px",
                          background: "none", border: "none",
                          borderBottom: activeTab === t.tabId ? `3px solid ${C.blue}` : "3px solid transparent",
                          color: activeTab === t.tabId ? C.blue : C.greyText,
                          fontWeight: activeTab === t.tabId ? 700 : 500,
                          fontSize: 12,
                          fontFamily: "var(--font-montserrat), Montserrat, sans-serif",
                          cursor: "pointer", minHeight: 44,
                          transition: "color 0.15s, border-color 0.15s",
                        }}
                      >
                        <span className="tab-label-full">{t.full}</span>
                        <span className="tab-label-short">{t.short}</span>
                      </button>
                    ))}
                  </div>

                  <div style={{ padding: "20px 22px" }}>
                    <div id="panel-accum" role="tabpanel" aria-labelledby="tab-accum"
                      tabIndex={0} hidden={activeTab !== "tab-accum"}>
                      <BarChart data={results.accumulationData} color={C.blue}
                        title={`Corpus growth — Age ${currentAge} to ${retirementAge}`}
                        subtitle={
                          isStepUp
                            ? `Step-Up SIP: starting ${formatINR(results.requiredMonthlySIP)}/mo, growing ${stepUpRate}%/yr for ${results.yearsToRetirement} years at ${preRetirementReturn}% p.a. return. Illustrative only.`
                            : `Flat SIP: ${formatINR(results.requiredMonthlySIP)}/month for ${results.yearsToRetirement} years at ${preRetirementReturn}% p.a. return. Illustrative only.`
                        } />
                    </div>

                    <div id="panel-drawdown" role="tabpanel" aria-labelledby="tab-drawdown"
                      tabIndex={0} hidden={activeTab !== "tab-drawdown"}>
                      <BarChart data={results.drawdownData} color={C.red}
                        title={`Corpus remaining — Age ${retirementAge} to ${lifeExpectancy}`}
                        subtitle={`Withdrawals inflation-adjusted at ${inflationRate}% p.a. Post-retirement return: ${postRetirementReturn}% p.a. Illustrative only.`} />
                      {results.isSustainable ? (
                        <div role="status" aria-live="polite" style={{
                          background: "#f0fdf4", border: "1px solid #86efac", borderRadius: 8,
                          padding: "8px 14px", marginTop: 12, fontSize: 12, color: "#166534",
                          fontFamily: "Arial, sans-serif",
                        }}>
                          ✓ Based on these assumptions, corpus sustains through age {lifeExpectancy}.
                          Remaining: {formatINR(results.remainingCorpus)}. Actual results may vary.
                        </div>
                      ) : (
                        <div role="alert" aria-live="assertive" style={{
                          background: "#fff1f2", border: "1px solid #fca5a5", borderRadius: 8,
                          padding: "8px 14px", marginTop: 12, fontSize: 12, color: "#991b1b",
                          fontFamily: "Arial, sans-serif",
                        }}>
                          ⚠ Based on these assumptions, corpus may deplete before age {lifeExpectancy}.
                          Consider increasing your SIP or revising assumptions.
                        </div>
                      )}
                    </div>

                    <div id="panel-table" role="tabpanel" aria-labelledby="tab-table"
                      tabIndex={0} hidden={activeTab !== "tab-table"}>
                      <div style={{ overflowX: "auto", maxHeight: 300, overflowY: "auto" }}>
                        <table style={{ width: "100%", borderCollapse: "collapse",
                          fontSize: 12, fontFamily: "Arial, sans-serif" }}
                          aria-label="Year-by-year corpus accumulation data">
                          <caption style={{ fontSize: 11, color: C.greyText, fontFamily: "Arial, sans-serif",
                            textAlign: "left", padding: "0 0 8px", captionSide: "top" }}>
                            Projected corpus value and cumulative investment each year. All figures are illustrative estimates.
                          </caption>
                          <thead>
                            <tr>
                              {(isStepUp
                                ? ["Age", "Year", "SIP This Year", "Total Invested", "Estimated Corpus"]
                                : ["Age", "Year", "Total Invested", "Estimated Corpus"]
                              ).map((h) => (
                                <th key={h} scope="col" style={{
                                  padding: "8px 10px", textAlign: "left",
                                  borderBottom: `2px solid ${C.blue}`, color: C.blue,
                                  fontSize: 11, fontFamily: "var(--font-montserrat), Montserrat, sans-serif",
                                  fontWeight: 700, whiteSpace: "nowrap",
                                  position: "sticky", top: 0, background: C.bgCard,
                                }}>{h}</th>
                              ))}
                            </tr>
                          </thead>
                          <tbody>
                            {results.accumulationData.map((d, i) => (
                              <tr key={d.age} style={{ background: i % 2 === 0 ? C.bgMuted : C.bgCard }}>
                                <td style={{ padding: "7px 10px", fontWeight: 700, color: C.blue }}>{d.age}</td>
                                <td style={{ padding: "7px 10px", color: C.greyText }}>{d.age - currentAge}</td>
                                {isStepUp && (
                                  <td style={{ padding: "7px 10px", color: C.blue, fontWeight: 600 }}>
                                    {formatINR(d.sipThisYear)}/mo
                                  </td>
                                )}
                                <td style={{ padding: "7px 10px" }}>{formatINR(d.invested)}</td>
                                <td style={{ padding: "7px 10px", fontWeight: 700, color: C.blueDark }}>{formatINR(d.corpus)}</td>
                              </tr>
                            ))}
                          </tbody>
                        </table>
                      </div>
                    </div>
                  </div>

                    {/* ── COMPARE PANEL ── */}
                    <div id="panel-compare" role="tabpanel" aria-labelledby="tab-compare"
                      tabIndex={0} hidden={activeTab !== "tab-compare"}>
                      {comparisonResults ? (
                        <div style={{ padding: "4px 0" }}>
                          <p style={{
                            fontSize: 11, color: C.greyText, fontFamily: "Verdana, Arial, sans-serif",
                            margin: "0 0 16px", lineHeight: 1.6,
                          }}>
                            Same corpus target. Two strategies. See which works better for you.
                            Step-Up SIP increases by <strong style={{ color: C.blue }}>{comparisonResults.stepUpRateUsed}%</strong> every year.
                          </p>

                          {/* Side-by-side cards */}
                          <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 12, marginBottom: 20 }}>
                            {/* Flat SIP card */}
                            <div style={{
                              background: "#f0fdf4", border: "2px solid #86efac",
                              borderRadius: 12, padding: "16px 18px",
                            }}>
                              <div style={{
                                fontSize: 10, fontWeight: 700, color: "#166534",
                                fontFamily: "Montserrat, sans-serif",
                                textTransform: "uppercase", letterSpacing: "0.1em", marginBottom: 10,
                              }}>
                                📊 Flat SIP
                              </div>
                              {[
                                { label: "Monthly SIP",    value: formatINR(comparisonResults.flat.requiredMonthlySIP), highlight: true },
                                { label: "SIP in Year 1",  value: formatINR(comparisonResults.flat.requiredMonthlySIP) },
                                { label: "SIP in Final Yr",value: formatINR(comparisonResults.flat.requiredMonthlySIP) },
                                { label: "Total Invested", value: formatINR(comparisonResults.flat.totalInvested) },
                                { label: "Corpus",         value: formatINR(comparisonResults.flat.retirementCorpus) },
                              ].map(({ label, value, highlight }) => (
                                <div key={label} style={{
                                  display: "flex", justifyContent: "space-between",
                                  padding: "5px 0", borderBottom: "1px solid #bbf7d0",
                                }}>
                                  <span style={{ fontSize: 11, color: "#166534", fontFamily: "Arial, sans-serif" }}>{label}</span>
                                  <span style={{
                                    fontSize: highlight ? 14 : 12, fontWeight: 800,
                                    color: "#166534", fontFamily: "Montserrat, sans-serif",
                                  }}>{value}</span>
                                </div>
                              ))}
                            </div>

                            {/* Step-Up SIP card */}
                            <div style={{
                              background: "#eff6ff", border: "2px solid #93c5fd",
                              borderRadius: 12, padding: "16px 18px",
                            }}>
                              <div style={{
                                fontSize: 10, fontWeight: 700, color: "#1d4ed8",
                                fontFamily: "Montserrat, sans-serif",
                                textTransform: "uppercase", letterSpacing: "0.1em", marginBottom: 10,
                              }}>
                                📈 Step-Up SIP ({comparisonResults.stepUpRateUsed}%/yr)
                              </div>
                              {[
                                { label: "Starting SIP",   value: formatINR(comparisonResults.stepup.requiredMonthlySIP), highlight: true },
                                { label: "SIP in Year 1",  value: formatINR(comparisonResults.stepup.requiredMonthlySIP) },
                                { label: "SIP in Final Yr",value: formatINR(comparisonResults.stepup.finalMonthlySIP) },
                                { label: "Total Invested", value: formatINR(comparisonResults.stepup.totalInvested) },
                                { label: "Corpus",         value: formatINR(comparisonResults.stepup.retirementCorpus) },
                              ].map(({ label, value, highlight }) => (
                                <div key={label} style={{
                                  display: "flex", justifyContent: "space-between",
                                  padding: "5px 0", borderBottom: "1px solid #bfdbfe",
                                }}>
                                  <span style={{ fontSize: 11, color: "#1d4ed8", fontFamily: "Arial, sans-serif" }}>{label}</span>
                                  <span style={{
                                    fontSize: highlight ? 14 : 12, fontWeight: 800,
                                    color: "#1d4ed8", fontFamily: "Montserrat, sans-serif",
                                  }}>{value}</span>
                                </div>
                              ))}
                            </div>
                          </div>

                          {/* Insight box */}
                          {(() => {
                            const flatSIP   = comparisonResults.flat.requiredMonthlySIP;
                            const stepSIP   = comparisonResults.stepup.requiredMonthlySIP;
                            const saving    = flatSIP - stepSIP;
                            const savingPct = Math.round((saving / flatSIP) * 100);
                            return saving > 0 ? (
                              <div role="status" style={{
                                background: "#eef3fb", border: "1.5px solid #c7d9f5",
                                borderRadius: 10, padding: "14px 18px",
                                fontSize: 12, color: C.blueDark,
                                fontFamily: "Verdana, Arial, sans-serif", lineHeight: 1.7,
                              }}>
                                <strong style={{ fontFamily: "Montserrat, sans-serif" }}>💡 Key Insight: </strong>
                                With Step-Up SIP, you start with <strong>{formatINR(stepSIP)}/mo</strong> instead
                                of <strong>{formatINR(flatSIP)}/mo</strong> — saving{" "}
                                <strong style={{ color: C.blue }}>{formatINR(saving)}/mo ({savingPct}%)</strong> in
                                the first year. Your SIP grows with your income, making it easier to start investing today.
                              </div>
                            ) : null;
                          })()}
                        </div>
                      ) : (
                        <p style={{ color: C.greyText, fontSize: 13, fontFamily: "Arial, sans-serif" }}>
                          Calculate your retirement plan to see the comparison.
                        </p>
                      )}
                    </div>
                </div>


              </div>
            )}
          </section>
        </main>
      </div>

      {/* ── PRINT SUMMARY (hidden on screen) ── */}
      <PrintSummary results={results} inputs={inputs} />

      {/* ── SHARE MODAL ── */}
      {showShare && results && (
        <ShareModal
          results={results}
          inputs={inputs}
          onClose={() => setShowShare(false)}
        />
      )}

      {/* ── SAVE PLAN MODAL ── */}
      {showSavePlan && results && (
        <SavePlanModal
          results={results}
          inputs={inputs}
          onClose={() => setShowSavePlan(false)}
          onSaved={() => setSavedCount((n) => n + 1)}
        />
      )}

      <style jsx>{`
        @media (max-width: 780px) {
          .calc-layout { grid-template-columns: 1fr !important; }
        }
        @media (max-width: 480px) {
          .calc-layout { padding: 14px 12px 40px !important; }
        }
      `}</style>
    </>
  );
}